apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
  - name: http
    protocol: TCP
    port: 9200
    targetPort: 9200
  - name: transport
    protocol: TCP
    port: 9300
    targetPort: 9300
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-headless
spec: 
  clusterIP: None
  selector:
    app: elasticsearch
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  serviceName: elasticsearch-headless
  template:
    metadata: 
      name: elasticsearch
      labels:
        app: elasticsearch
      annotations:
        co.elastic.metrics.elasticsearch/module: elasticsearch
        co.elastic.metrics.elasticsearch/hosts: "${data.host}:9200"
    spec:
      initContainers:
        - name: fix-the-volume-permission
          image: busybox
          command:
          - sh
          - -c
          - chown -R 1000:1000 /usr/share/elasticsearch/data
          securityContext:
            privileged: true
          volumeMounts:
          - name: data
            mountPath: /usr/share/elasticsearch/data
        - name: increase-the-vm-max-map-count
          image: busybox
          command:
          - sysctl
          - -w
          - vm.max_map_count=262144
          securityContext:
            privileged: true
        - name: increase-the-ulimit
          image: busybox
          command:
          - sh
          - -c
          - ulimit -n 65536
          securityContext:
            privileged: true
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0-alpha1-SNAPSHOT
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 3
          timeoutSeconds: 5
          exec:
            command: 
              - sh
              - -c
              - "curl http://${HOSTNAME}:9200/_cluster/health"
        ports:
        - name: http
          containerPort: 9200
        - name: transport
          containerPort: 9300
        env:
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: path.data
            value: "/usr/share/elasticsearch/data/${node.name}"
          - name: discovery.zen.minimum_master_nodes 
            value: "1"
          - name: network.host
            value: "_site_"
          - name: discovery.zen.ping.unicast.hosts
            value: "elasticsearch"
          - name: cluster.name
            value: "elasticsearch"
          - name: ES_JAVA_OPTS
            value: -Xmx1g -Xms1g
          - name: node.data
            value: "true"
          - name: node.ingest
            value: "true"
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: data
          hostPath:
            path: /var/lib/elasticsearch-data
