apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana
  labels:
    run: kibana
    name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kibana
  template:
    metadata:
      labels:
        run: kibana
      annotations:
        co.elastic.metrics.kibana/module: kibana
        co.elastic.metrics.kibana/hosts: "${data.host}:5601"
    spec:
      initContainers:
        - name: wait-elasticsearch
          image: busybox
          command:
            - sh
            - -c
            - until nslookup monitored-cluster; do echo waiting for monitored-cluster; sleep 2; done;
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.0.0-alpha1-SNAPSHOT
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://monitored-cluster:9200
        ports:
        - containerPort: 5601
          hostPort: 5601
          name: ui
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    service: kibana
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    run: kibana
  type: NodePort
